[package]
name = "ramp-graph"
description = "Log-structured transactional graph database"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]

[dev-dependencies]

[lints]
workspace = true
