[package]
name = "ramp-graph"
description = "Log-structured transactional graph database"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
heed.workspace = true
regex.workspace = true
rmp-serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
tempfile.workspace = true

[lints]
workspace = true

[[bench]]
name = "insert"
harness = false

[[bench]]
name = "query"
harness = false

[[bench]]
name = "stream"
harness = false
